; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const SPECIAL_MAP        ; 00
; Johto landmarks
	const NEPHI_CITY         ; 01
	const ROUTE_I15           ; 02
	const PROVO_CITY   ; 03
	const BYU_CAMPUS    ; 04
	const MTC_CAMPUS           ; 05
	const BYU_UNDERGROUND           ; 06
	const UTAH_LAKE        ; 07
	const OREM_CITY       ; 08
	const GENEVA_STEEL_PLANT   ; 09
	const PROVO_CANYON      ; 0a
	const TIMPANOGOS_PASS           ; 0b
	const HEBER_CITY     ; 0c
	const ROUTE_US40         ; 0d
	const DUCHESNE_CITY           ; 0e
	const ROUTE_87        ; 0f
	const VERNAL_CITY      ; 10
	const EXCAVATION_SITE        ; 11
	const ROUTE_191           ; 12
	const CARBON_POWER_PLANT     ; 13
	const CARBON_ROAD       ; 14
	const PRICE_CITY        ; 15
	const ROUTE_55     ; 16
	const SALT_LAKE_VALLEY        ; 17
	const MILLCREEK_CANYON   ; 18
	const ROUTE_I80_EAST      ; 19
	const TOOLE_CITY           ; 1a
	const SALT_FLATS     ; 1b
	const WENDOVER_CITY      ; 1c
	const SALT_LAKE_CITY           ; 1d
	const TEMPLE_SQUARE           ; 1e
	const ANTELOPE_ISLAND      ; 1f
	const GREAT_SALT_LAKE    ; 20
	const ROUTE_I80_WEST          ; 21
	const PARK_CITY       ; 22
	const PARK_CITY_SLOPES           ; 23
	const JORDANELLE_PASS           ; 24
	const UTAH_POINT       ; 25
	const MOUNT_TIMPANOGOS         ; 26
	const TIMPANOGOS_CAVE           ; 27
	const ROUTE_67       ; 28
	const OGDEN_CITY      ; 29
	const UNION_STATION           ; 2a
	const ROUTE_US89      ; 2b
	const LOGAN_CITY    ; 2c
	const BEAR_LAKE_PASS           ; 2d
	const BEAR_LAKE         ; 2e
KANTO_LANDMARK EQU const_value
	const ROUTE_48           ; 2f
	const YELLOW_FOREST      ; 30
	const QUIET_CAVE         ; 31
	const ROUTE_42           ; 32
	const MT_MORTAR          ; 33
	const MAHOGANY_TOWN      ; 34
	const ROUTE_43           ; 35
	const LAKE_OF_RAGE       ; 36
	const ROUTE_44           ; 37
	const ICE_PATH           ; 38
	const BLACKTHORN_CITY    ; 39
	const DRAGONS_DEN        ; 3a
	const ROUTE_45           ; 3b
	const DARK_CAVE          ; 3c
	const ROUTE_46           ; 3d
	const SILVER_CAVE        ; 3e
	const FAST_SHIP          ; 3f
	const SINJOH_RUINS       ; 40
	const MYSTRI_STAGE       ; 41
	const PALLET_TOWN        ; 42
	const ROUTE_1            ; 43
	const VIRIDIAN_CITY      ; 44
	const ROUTE_2            ; 45
	const VIRIDIAN_FOREST    ; 46
	const PEWTER_CITY        ; 47
	const ROUTE_3            ; 48
	const MT_MOON            ; 49
	const ROUTE_4            ; 4a
	const CERULEAN_CITY      ; 4b
	const CERULEAN_CAVE      ; 4c
	const ROUTE_24           ; 4d
	const ROUTE_25           ; 4e
	const CERULEAN_CAPE      ; 4f
	const ROUTE_5            ; 50
	const UNDERGROUND        ; 51
	const ROUTE_6            ; 52
	const VERMILION_CITY     ; 53
	const DIGLETTS_CAVE      ; 54
	const ROUTE_7            ; 55
	const ROUTE_8            ; 56
	const ROUTE_9            ; 57
	const ROUTE_10           ; 58
	const ROCK_TUNNEL        ; 59
	const POWER_PLANT        ; 5a
	const DIM_CAVE           ; 5b
	const LAVENDER_TOWN      ; 5c
	const LAV_SALT_LAKE_VALLEY    ; 5d
	const SOUL_HOUSE         ; 5e
	const CELADON_CITY       ; 5f
	const CELADON_UNIVERSITY ; 60
	const CELADON_OUTSKIRTS  ; 61
	const SAFFRON_CITY       ; 62
	const ROUTE_11           ; 63
	const ROUTE_12           ; 64
	const ROUTE_13           ; 65
	const ROUTE_14           ; 66
	const ROUTE_15           ; 67
	const LUCKY_ISLAND       ; 68
	const ROUTE_16           ; 69
	const ROUTE_17           ; 6a
	const ROUTE_18           ; 6b
	const FUCHSIA_CITY       ; 6c
	const SAFARI_ZONE        ; 6d
	const URAGA_CHANNEL      ; 6e
	const SCARY_CAVE         ; 6f
	const ROUTE_19           ; 70
	const ROUTE_20           ; 71
	const SEAFOAM_ISLANDS    ; 72
	const CINNABAR_ISLAND    ; 73
	const POKEMON_MANSION    ; 74
	const CINNABAR_VOLCANO   ; 75
	const ROUTE_21           ; 76
	const ROUTE_22           ; 77
	const ROUTE_27           ; 78
	const TOHJO_FALLS        ; 79
	const ROUTE_26           ; 7a
	const POKEMON_LEAGUE     ; 7b
	const ROUTE_23           ; 7c
	const VICTORY_ROAD       ; 7d
	const INDIGO_PLATEAU     ; 7e
	const ROUTE_28           ; 7f
	const CINNABAR_LAB       ; 80
SHAMOUTI_LANDMARK EQU const_value
	const SHAMOUTI_ISLAND    ; 81
	const BEAUTIFUL_BEACH    ; 82
	const ROCKY_BEACH        ; 83
	const NOISY_FOREST       ; 84
	const SHRINE_RUINS       ; 85
	const SHAMOUTI_TUNNEL    ; 86
	const WARM_BEACH         ; 87
	const SHAMOUTI_COAST     ; 88
	const FIRE_ISLAND        ; 89
	const ICE_ISLAND         ; 8a
	const LIGHTNING_ISLAND   ; 8b
	const ROUTE_49           ; 8c
	const VALENCIA_ISLAND    ; 8d
	const NAVEL_ROCK         ; 8e
	const FARAWAY_ISLAND     ; 8f
NUM_LANDMARKS EQU const_value

; used in CaughtData
LANDMARK_EVENT EQU $ff

; Regions
	const_def
	const JOHTO_REGION  ; 0
	const KANTO_REGION  ; 1
	const ORANGE_REGION ; 2
NUM_REGIONS EQU const_value
