name: Nightly build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt-get install make python gcc git bison
        git clone -b v0.6.0 --depth=1 https://github.com/gbdev/rgbds
        pushd rgbds
        sudo make install
        popd
    - name: Build hyperdriveguy/deseret-crystal
      run: |
        git clone "https://hyperdriveguy:$GITHUB_TOKEN@github.com/hyperdriveguy/deseret-crystal.git"
        pushd deseret-crystal
        mkdir build
        make -j4
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-3.0.0-beta.sym
        make tidy
        make -j4 faithful
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-faithful-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-faithful-3.0.0-beta.sym
        make tidy
        make -j4 debug
        mv polishedcrystal-3.0.0-beta.gbc build/polisheddebug-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polisheddebug-3.0.0-beta.sym
        make tidy
        make -j4 faithful debug
        mv polishedcrystal-3.0.0-beta.gbc build/polisheddebug-faithful-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polisheddebug-faithful-3.0.0-beta.sym
        make tidy
        make bsp
        mv polishedcrystal-3.0.0-beta.bsp build/polishedcrystal-savepatch-3.0.0-beta.bsp
        popd
    - name: Delete old release
      id: delete_release
      uses: jagger27/delete-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-release
    - name: Advance nightly tag to master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pushd deseret-crystal
        git tag nightly-release -f
        git push --tags -f "https://hyperdriveguy:$GITHUB_TOKEN@github.com/hyperdriveguy/deseret-crystal.git"
        popd
    - name: Create new release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-release
        release_name: Nightly Release
        body: |
          This is the current Deseret Crystal **alpha** release. The assets all have an 8-character "commit hash" at the end to identify the exact code they're built from.
          
          The **.gbc** assets are ROMs. If you just want to play the game, download one (regular or `-faithful`) and load it in [BGB](https://bgb.bircd.org/), [mGBA](https://mgba.io/), [Gambatte](https://github.com/sinamas/gambatte), or another accurate Game Boy Color emulator. (***Do not use VBA*** or VBA-M.)
          
          The **.sym** assets are "symbol files". They're useful for debugging, or for [discovering cheat codes](https://github.com/pret/pokecrystal/wiki/Discovering-GameShark-cheat-codes), although cheats are *not* officially supported and may cause bugs or crashes. (Do ***not*** ask the developers for cheat codes.)
          
          The **.bsp** asset is a [BSP](https://github.com/aaaaaa123456789/bsp) save file patch in case you need to upgrade a save file from an older nightly build, using a patcher like the one for [Pokémon Prism](http://pokemonprism.com/patcher.html).
          Note that this save patch doesn't really do anything at the moment. Development is so early that it doesn't make sense to attempt to port saves yet.
          
          The **deseret-crystal-debug** assets are ROMs and symbol files with extra features to help debug the game. Do ***not*** download these to just play with; use them to help the developers diagnose and fix bugs, or create new features.
        draft: false
        prerelease: true
    - name: Upload ROM
      id: upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polishedcrystal-3.0.0-beta.gbc
        asset_name: deseret-crystal-alpha-${{ env.SHORT_SHA }}.gbc
        asset_content_type: application/octet-stream
    - name: Upload SYM
      id: upload-sym
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polishedcrystal-3.0.0-beta.sym
        asset_name: deseret-crystal-alpha-${{ env.SHORT_SHA }}.sym
        asset_content_type: text/plain
    - name: Upload faithful ROM
      id: upload-faithful
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polishedcrystal-faithful-3.0.0-beta.gbc
        asset_name: deseret-crystal-faithful-alpha-${{ env.SHORT_SHA }}.gbc
        asset_content_type: application/octet-stream
    - name: Upload faithful SYM
      id: upload-faithful-sym
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polishedcrystal-faithful-3.0.0-beta.sym
        asset_name: deseret-crystal-faithful-alpha-${{ env.SHORT_SHA }}.sym
        asset_content_type: text/plain
    - name: Upload debug ROM
      id: upload-debug
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polisheddebug-3.0.0-beta.gbc
        asset_name: deseret-crystal-debug-alpha-${{ env.SHORT_SHA }}.gbc
        asset_content_type: application/octet-stream
    - name: Upload debug SYM
      id: upload-debug-sym
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polisheddebug-3.0.0-beta.sym
        asset_name: deseret-crystal-debug-alpha-${{ env.SHORT_SHA }}.sym
        asset_content_type: text/plain
    - name: Upload faithful debug ROM
      id: upload-faithful-debug
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polisheddebug-faithful-3.0.0-beta.gbc
        asset_name: deseret-crystal-faithful-debug-alpha-${{ env.SHORT_SHA }}.gbc
        asset_content_type: application/octet-stream
    - name: Upload faithful debug SYM
      id: upload-faithful-debug-sym
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polisheddebug-faithful-3.0.0-beta.sym
        asset_name: deseret-crystal-faithful-debug-alpha-${{ env.SHORT_SHA }}.sym
        asset_content_type: text/plain
    - name: Upload BSP
      id: upload-bsp
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./deseret-crystal/build/polishedcrystal-savepatch-3.0.0-beta.bsp
        asset_name: deseret-crystal-savepatch-alpha-${{ env.SHORT_SHA }}.bsp
        asset_content_type: application/octet-stream
